# Generated by Django 5.0.6 on 2024-07-12 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("youtube_title", models.CharField(max_length=300)),
                ("youtube_url", models.URLField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("blog", "Blog Content"),
                            ("linkedin", "LinkedIn Content"),
                            ("tweet", "Tweet Content"),
                        ],
                        default="blog",
                        max_length=20,
                    ),
                ),
                ("generated_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.UniqueConstraint(
                fields=("user", "youtube_title", "content_type"),
                name="unique_user_youtube_content",
            ),
        ),
    ]
